
package com.base.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://server.webservice.base.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://server.webservice.base.com/Hello/printContextRequest", output = "http://server.webservice.base.com/Hello/printContextResponse")
    public void printContext();

    /**
     * 
     * @param customer
     * @return
     *     returns com.base.webservice.client.Customer
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.webservice.base.com/Hello/selectCustomerByNameRequest", output = "http://server.webservice.base.com/Hello/selectCustomerByNameResponse")
    public Customer selectCustomerByName(
        @WebParam(name = "customer", partName = "customer")
        Customer customer);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.base.webservice.client.Customer
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.webservice.base.com/Hello/selectMaxAgeCustomerRequest", output = "http://server.webservice.base.com/Hello/selectMaxAgeCustomerResponse")
    public Customer selectMaxAgeCustomer(
        @WebParam(name = "arg0", partName = "arg0")
        Customer arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Customer arg1);

}
